### PR TITLE
Create internal API for changing width and height

### PR DESCRIPTION
**Pull request by tulioag**
Will be used in https://github.com/vaadin/vaadin-confirm-dialog-flow to fix issue https://github.com/vaadin/vaadin-confirm-dialog-flow/issues/40

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog/84)

### CODE REVIEW

**Comment by alvarezguille** [comment]
*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog/84#-LhAMT0g9rGQMf_J1qtb:-LhAMT0h5w5MFVpQJVir:b-4bd3j9) (no related file):*
Can we have tests for the change?

---

**Comment by heruan** [comment]
What's the status of this? Will this be in V14?

**Comment by tulioag** [comment]
It's still in progress. Since it is a bugfix, it will be in v14 even if it doesn't make it to `14.0.0`

**Comment by heruan** [comment]
What's the status of this?

**Pull request merged**
